// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kv.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Internal representations for operations.
type Op int32

const (
	Op_GET   Op = 0
	Op_SET   Op = 1
	Op_CLEAR Op = 2
	Op_CAS   Op = 3
)

var Op_name = map[int32]string{
	0: "GET",
	1: "SET",
	2: "CLEAR",
	3: "CAS",
}

var Op_value = map[string]int32{
	"GET":   0,
	"SET":   1,
	"CLEAR": 2,
	"CAS":   3,
}

func (x Op) String() string {
	return proto.EnumName(Op_name, int32(x))
}

func (Op) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{0}
}

// Represents a single key, used for gets.
type Key struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Key) Reset()         { *m = Key{} }
func (m *Key) String() string { return proto.CompactTextString(m) }
func (*Key) ProtoMessage()    {}
func (*Key) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{0}
}

func (m *Key) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Key.Unmarshal(m, b)
}
func (m *Key) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Key.Marshal(b, m, deterministic)
}
func (m *Key) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Key.Merge(m, src)
}
func (m *Key) XXX_Size() int {
	return xxx_messageInfo_Key.Size(m)
}
func (m *Key) XXX_DiscardUnknown() {
	xxx_messageInfo_Key.DiscardUnknown(m)
}

var xxx_messageInfo_Key proto.InternalMessageInfo

func (m *Key) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

// Represents a single value, can be used for put etc.
type Value struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Value) Reset()         { *m = Value{} }
func (m *Value) String() string { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()    {}
func (*Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{1}
}

func (m *Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Value.Unmarshal(m, b)
}
func (m *Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Value.Marshal(b, m, deterministic)
}
func (m *Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Value.Merge(m, src)
}
func (m *Value) XXX_Size() int {
	return xxx_messageInfo_Value.Size(m)
}
func (m *Value) XXX_DiscardUnknown() {
	xxx_messageInfo_Value.DiscardUnknown(m)
}

var xxx_messageInfo_Value proto.InternalMessageInfo

func (m *Value) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// Represent a key-value pair that is used to return results.
type KeyValue struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyValue) Reset()         { *m = KeyValue{} }
func (m *KeyValue) String() string { return proto.CompactTextString(m) }
func (*KeyValue) ProtoMessage()    {}
func (*KeyValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{2}
}

func (m *KeyValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyValue.Unmarshal(m, b)
}
func (m *KeyValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyValue.Marshal(b, m, deterministic)
}
func (m *KeyValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyValue.Merge(m, src)
}
func (m *KeyValue) XXX_Size() int {
	return xxx_messageInfo_KeyValue.Size(m)
}
func (m *KeyValue) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyValue.DiscardUnknown(m)
}

var xxx_messageInfo_KeyValue proto.InternalMessageInfo

func (m *KeyValue) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KeyValue) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// Represent a void message indicating success
type Success struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Success) Reset()         { *m = Success{} }
func (m *Success) String() string { return proto.CompactTextString(m) }
func (*Success) ProtoMessage()    {}
func (*Success) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{3}
}

func (m *Success) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Success.Unmarshal(m, b)
}
func (m *Success) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Success.Marshal(b, m, deterministic)
}
func (m *Success) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Success.Merge(m, src)
}
func (m *Success) XXX_Size() int {
	return xxx_messageInfo_Success.Size(m)
}
func (m *Success) XXX_DiscardUnknown() {
	xxx_messageInfo_Success.DiscardUnknown(m)
}

var xxx_messageInfo_Success proto.InternalMessageInfo

// Represents an error.
type Error struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{4}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

// Represents an argument for CAS
type CASArg struct {
	Kv                   *KeyValue `protobuf:"bytes,1,opt,name=kv,proto3" json:"kv,omitempty"`
	Value                *Value    `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CASArg) Reset()         { *m = CASArg{} }
func (m *CASArg) String() string { return proto.CompactTextString(m) }
func (*CASArg) ProtoMessage()    {}
func (*CASArg) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{5}
}

func (m *CASArg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CASArg.Unmarshal(m, b)
}
func (m *CASArg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CASArg.Marshal(b, m, deterministic)
}
func (m *CASArg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CASArg.Merge(m, src)
}
func (m *CASArg) XXX_Size() int {
	return xxx_messageInfo_CASArg.Size(m)
}
func (m *CASArg) XXX_DiscardUnknown() {
	xxx_messageInfo_CASArg.DiscardUnknown(m)
}

var xxx_messageInfo_CASArg proto.InternalMessageInfo

func (m *CASArg) GetKv() *KeyValue {
	if m != nil {
		return m.Kv
	}
	return nil
}

func (m *CASArg) GetValue() *Value {
	if m != nil {
		return m.Value
	}
	return nil
}

// Represents an empty message
type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{6}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

// Represents a case where we need the client to connect
// to another server.
type Redirect struct {
	Server               string   `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Redirect) Reset()         { *m = Redirect{} }
func (m *Redirect) String() string { return proto.CompactTextString(m) }
func (*Redirect) ProtoMessage()    {}
func (*Redirect) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{7}
}

func (m *Redirect) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Redirect.Unmarshal(m, b)
}
func (m *Redirect) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Redirect.Marshal(b, m, deterministic)
}
func (m *Redirect) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Redirect.Merge(m, src)
}
func (m *Redirect) XXX_Size() int {
	return xxx_messageInfo_Redirect.Size(m)
}
func (m *Redirect) XXX_DiscardUnknown() {
	xxx_messageInfo_Redirect.DiscardUnknown(m)
}

var xxx_messageInfo_Redirect proto.InternalMessageInfo

func (m *Redirect) GetServer() string {
	if m != nil {
		return m.Server
	}
	return ""
}

// Represents an operation result.
type Result struct {
	// Types that are valid to be assigned to Result:
	//	*Result_Redirect
	//	*Result_Kv
	//	*Result_S
	Result               isResult_Result `protobuf_oneof:"result"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{8}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

type isResult_Result interface {
	isResult_Result()
}

type Result_Redirect struct {
	Redirect *Redirect `protobuf:"bytes,1,opt,name=redirect,proto3,oneof"`
}

type Result_Kv struct {
	Kv *KeyValue `protobuf:"bytes,2,opt,name=kv,proto3,oneof"`
}

type Result_S struct {
	S *Success `protobuf:"bytes,3,opt,name=s,proto3,oneof"`
}

func (*Result_Redirect) isResult_Result() {}

func (*Result_Kv) isResult_Result() {}

func (*Result_S) isResult_Result() {}

func (m *Result) GetResult() isResult_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *Result) GetRedirect() *Redirect {
	if x, ok := m.GetResult().(*Result_Redirect); ok {
		return x.Redirect
	}
	return nil
}

func (m *Result) GetKv() *KeyValue {
	if x, ok := m.GetResult().(*Result_Kv); ok {
		return x.Kv
	}
	return nil
}

func (m *Result) GetS() *Success {
	if x, ok := m.GetResult().(*Result_S); ok {
		return x.S
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Result) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Result_Redirect)(nil),
		(*Result_Kv)(nil),
		(*Result_S)(nil),
	}
}

// A type for arguments across all operations
type Command struct {
	Operation Op `protobuf:"varint,1,opt,name=operation,proto3,enum=pb.Op" json:"operation,omitempty"`
	// Types that are valid to be assigned to Arg:
	//	*Command_Get
	//	*Command_Set
	//	*Command_Clear
	//	*Command_Cas
	Arg                  isCommand_Arg `protobuf_oneof:"arg"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Command) Reset()         { *m = Command{} }
func (m *Command) String() string { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()    {}
func (*Command) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{9}
}

func (m *Command) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Command.Unmarshal(m, b)
}
func (m *Command) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Command.Marshal(b, m, deterministic)
}
func (m *Command) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Command.Merge(m, src)
}
func (m *Command) XXX_Size() int {
	return xxx_messageInfo_Command.Size(m)
}
func (m *Command) XXX_DiscardUnknown() {
	xxx_messageInfo_Command.DiscardUnknown(m)
}

var xxx_messageInfo_Command proto.InternalMessageInfo

func (m *Command) GetOperation() Op {
	if m != nil {
		return m.Operation
	}
	return Op_GET
}

type isCommand_Arg interface {
	isCommand_Arg()
}

type Command_Get struct {
	Get *Key `protobuf:"bytes,2,opt,name=get,proto3,oneof"`
}

type Command_Set struct {
	Set *KeyValue `protobuf:"bytes,3,opt,name=set,proto3,oneof"`
}

type Command_Clear struct {
	Clear *Empty `protobuf:"bytes,4,opt,name=clear,proto3,oneof"`
}

type Command_Cas struct {
	Cas *CASArg `protobuf:"bytes,5,opt,name=cas,proto3,oneof"`
}

func (*Command_Get) isCommand_Arg() {}

func (*Command_Set) isCommand_Arg() {}

func (*Command_Clear) isCommand_Arg() {}

func (*Command_Cas) isCommand_Arg() {}

func (m *Command) GetArg() isCommand_Arg {
	if m != nil {
		return m.Arg
	}
	return nil
}

func (m *Command) GetGet() *Key {
	if x, ok := m.GetArg().(*Command_Get); ok {
		return x.Get
	}
	return nil
}

func (m *Command) GetSet() *KeyValue {
	if x, ok := m.GetArg().(*Command_Set); ok {
		return x.Set
	}
	return nil
}

func (m *Command) GetClear() *Empty {
	if x, ok := m.GetArg().(*Command_Clear); ok {
		return x.Clear
	}
	return nil
}

func (m *Command) GetCas() *CASArg {
	if x, ok := m.GetArg().(*Command_Cas); ok {
		return x.Cas
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Command) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Command_Get)(nil),
		(*Command_Set)(nil),
		(*Command_Clear)(nil),
		(*Command_Cas)(nil),
	}
}

// A log entry
type Entry struct {
	Term                 int64    `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Index                int64    `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Cmd                  *Command `protobuf:"bytes,3,opt,name=cmd,proto3" json:"cmd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Entry) Reset()         { *m = Entry{} }
func (m *Entry) String() string { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()    {}
func (*Entry) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{10}
}

func (m *Entry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entry.Unmarshal(m, b)
}
func (m *Entry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entry.Marshal(b, m, deterministic)
}
func (m *Entry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entry.Merge(m, src)
}
func (m *Entry) XXX_Size() int {
	return xxx_messageInfo_Entry.Size(m)
}
func (m *Entry) XXX_DiscardUnknown() {
	xxx_messageInfo_Entry.DiscardUnknown(m)
}

var xxx_messageInfo_Entry proto.InternalMessageInfo

func (m *Entry) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *Entry) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Entry) GetCmd() *Command {
	if m != nil {
		return m.Cmd
	}
	return nil
}

type ClientRequest struct {
	Cmd                  *Command `protobuf:"bytes,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Timestamp            int64    `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ClientID             string   `protobuf:"bytes,3,opt,name=clientID,proto3" json:"clientID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientRequest) Reset()         { *m = ClientRequest{} }
func (m *ClientRequest) String() string { return proto.CompactTextString(m) }
func (*ClientRequest) ProtoMessage()    {}
func (*ClientRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{11}
}

func (m *ClientRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientRequest.Unmarshal(m, b)
}
func (m *ClientRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientRequest.Marshal(b, m, deterministic)
}
func (m *ClientRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientRequest.Merge(m, src)
}
func (m *ClientRequest) XXX_Size() int {
	return xxx_messageInfo_ClientRequest.Size(m)
}
func (m *ClientRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClientRequest proto.InternalMessageInfo

func (m *ClientRequest) GetCmd() *Command {
	if m != nil {
		return m.Cmd
	}
	return nil
}

func (m *ClientRequest) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *ClientRequest) GetClientID() string {
	if m != nil {
		return m.ClientID
	}
	return ""
}

type PrePrepareMsg struct {
	ViewId               int64          `protobuf:"varint,1,opt,name=viewId,proto3" json:"viewId,omitempty"`
	SequenceID           int64          `protobuf:"varint,2,opt,name=sequenceID,proto3" json:"sequenceID,omitempty"`
	Digest               string         `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	Request              *ClientRequest `protobuf:"bytes,4,opt,name=request,proto3" json:"request,omitempty"`
	Node                 string         `protobuf:"bytes,5,opt,name=node,proto3" json:"node,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PrePrepareMsg) Reset()         { *m = PrePrepareMsg{} }
func (m *PrePrepareMsg) String() string { return proto.CompactTextString(m) }
func (*PrePrepareMsg) ProtoMessage()    {}
func (*PrePrepareMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{12}
}

func (m *PrePrepareMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrePrepareMsg.Unmarshal(m, b)
}
func (m *PrePrepareMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrePrepareMsg.Marshal(b, m, deterministic)
}
func (m *PrePrepareMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrePrepareMsg.Merge(m, src)
}
func (m *PrePrepareMsg) XXX_Size() int {
	return xxx_messageInfo_PrePrepareMsg.Size(m)
}
func (m *PrePrepareMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_PrePrepareMsg.DiscardUnknown(m)
}

var xxx_messageInfo_PrePrepareMsg proto.InternalMessageInfo

func (m *PrePrepareMsg) GetViewId() int64 {
	if m != nil {
		return m.ViewId
	}
	return 0
}

func (m *PrePrepareMsg) GetSequenceID() int64 {
	if m != nil {
		return m.SequenceID
	}
	return 0
}

func (m *PrePrepareMsg) GetDigest() string {
	if m != nil {
		return m.Digest
	}
	return ""
}

func (m *PrePrepareMsg) GetRequest() *ClientRequest {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *PrePrepareMsg) GetNode() string {
	if m != nil {
		return m.Node
	}
	return ""
}

type PrepareMsg struct {
	ViewId               int64    `protobuf:"varint,1,opt,name=viewId,proto3" json:"viewId,omitempty"`
	SequenceID           int64    `protobuf:"varint,2,opt,name=sequenceID,proto3" json:"sequenceID,omitempty"`
	Digest               string   `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	Node                 string   `protobuf:"bytes,4,opt,name=node,proto3" json:"node,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrepareMsg) Reset()         { *m = PrepareMsg{} }
func (m *PrepareMsg) String() string { return proto.CompactTextString(m) }
func (*PrepareMsg) ProtoMessage()    {}
func (*PrepareMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{13}
}

func (m *PrepareMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrepareMsg.Unmarshal(m, b)
}
func (m *PrepareMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrepareMsg.Marshal(b, m, deterministic)
}
func (m *PrepareMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrepareMsg.Merge(m, src)
}
func (m *PrepareMsg) XXX_Size() int {
	return xxx_messageInfo_PrepareMsg.Size(m)
}
func (m *PrepareMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_PrepareMsg.DiscardUnknown(m)
}

var xxx_messageInfo_PrepareMsg proto.InternalMessageInfo

func (m *PrepareMsg) GetViewId() int64 {
	if m != nil {
		return m.ViewId
	}
	return 0
}

func (m *PrepareMsg) GetSequenceID() int64 {
	if m != nil {
		return m.SequenceID
	}
	return 0
}

func (m *PrepareMsg) GetDigest() string {
	if m != nil {
		return m.Digest
	}
	return ""
}

func (m *PrepareMsg) GetNode() string {
	if m != nil {
		return m.Node
	}
	return ""
}

type CommitMsg struct {
	ViewId               int64    `protobuf:"varint,1,opt,name=viewId,proto3" json:"viewId,omitempty"`
	SequenceID           int64    `protobuf:"varint,2,opt,name=sequenceID,proto3" json:"sequenceID,omitempty"`
	Digest               string   `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	Node                 string   `protobuf:"bytes,4,opt,name=node,proto3" json:"node,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommitMsg) Reset()         { *m = CommitMsg{} }
func (m *CommitMsg) String() string { return proto.CompactTextString(m) }
func (*CommitMsg) ProtoMessage()    {}
func (*CommitMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{14}
}

func (m *CommitMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitMsg.Unmarshal(m, b)
}
func (m *CommitMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitMsg.Marshal(b, m, deterministic)
}
func (m *CommitMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitMsg.Merge(m, src)
}
func (m *CommitMsg) XXX_Size() int {
	return xxx_messageInfo_CommitMsg.Size(m)
}
func (m *CommitMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitMsg.DiscardUnknown(m)
}

var xxx_messageInfo_CommitMsg proto.InternalMessageInfo

func (m *CommitMsg) GetViewId() int64 {
	if m != nil {
		return m.ViewId
	}
	return 0
}

func (m *CommitMsg) GetSequenceID() int64 {
	if m != nil {
		return m.SequenceID
	}
	return 0
}

func (m *CommitMsg) GetDigest() string {
	if m != nil {
		return m.Digest
	}
	return ""
}

func (m *CommitMsg) GetNode() string {
	if m != nil {
		return m.Node
	}
	return ""
}

type ViewChangeMsg struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	NewView              int64    `protobuf:"varint,2,opt,name=newView,proto3" json:"newView,omitempty"`
	LastSequenceID       int64    `protobuf:"varint,3,opt,name=lastSequenceID,proto3" json:"lastSequenceID,omitempty"`
	Node                 string   `protobuf:"bytes,5,opt,name=node,proto3" json:"node,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ViewChangeMsg) Reset()         { *m = ViewChangeMsg{} }
func (m *ViewChangeMsg) String() string { return proto.CompactTextString(m) }
func (*ViewChangeMsg) ProtoMessage()    {}
func (*ViewChangeMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{15}
}

func (m *ViewChangeMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ViewChangeMsg.Unmarshal(m, b)
}
func (m *ViewChangeMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ViewChangeMsg.Marshal(b, m, deterministic)
}
func (m *ViewChangeMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ViewChangeMsg.Merge(m, src)
}
func (m *ViewChangeMsg) XXX_Size() int {
	return xxx_messageInfo_ViewChangeMsg.Size(m)
}
func (m *ViewChangeMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ViewChangeMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ViewChangeMsg proto.InternalMessageInfo

func (m *ViewChangeMsg) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ViewChangeMsg) GetNewView() int64 {
	if m != nil {
		return m.NewView
	}
	return 0
}

func (m *ViewChangeMsg) GetLastSequenceID() int64 {
	if m != nil {
		return m.LastSequenceID
	}
	return 0
}

func (m *ViewChangeMsg) GetNode() string {
	if m != nil {
		return m.Node
	}
	return ""
}

// Response to client
type ClientResponse struct {
	ViewId               int64    `protobuf:"varint,1,opt,name=viewId,proto3" json:"viewId,omitempty"`
	Timestamp            int64    `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ClientID             string   `protobuf:"bytes,3,opt,name=clientID,proto3" json:"clientID,omitempty"`
	Node                 string   `protobuf:"bytes,4,opt,name=node,proto3" json:"node,omitempty"`
	NodeResult           *Result  `protobuf:"bytes,5,opt,name=nodeResult,proto3" json:"nodeResult,omitempty"`
	SequenceID           int64    `protobuf:"varint,6,opt,name=sequenceID,proto3" json:"sequenceID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientResponse) Reset()         { *m = ClientResponse{} }
func (m *ClientResponse) String() string { return proto.CompactTextString(m) }
func (*ClientResponse) ProtoMessage()    {}
func (*ClientResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{16}
}

func (m *ClientResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientResponse.Unmarshal(m, b)
}
func (m *ClientResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientResponse.Marshal(b, m, deterministic)
}
func (m *ClientResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientResponse.Merge(m, src)
}
func (m *ClientResponse) XXX_Size() int {
	return xxx_messageInfo_ClientResponse.Size(m)
}
func (m *ClientResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ClientResponse proto.InternalMessageInfo

func (m *ClientResponse) GetViewId() int64 {
	if m != nil {
		return m.ViewId
	}
	return 0
}

func (m *ClientResponse) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *ClientResponse) GetClientID() string {
	if m != nil {
		return m.ClientID
	}
	return ""
}

func (m *ClientResponse) GetNode() string {
	if m != nil {
		return m.Node
	}
	return ""
}

func (m *ClientResponse) GetNodeResult() *Result {
	if m != nil {
		return m.NodeResult
	}
	return nil
}

func (m *ClientResponse) GetSequenceID() int64 {
	if m != nil {
		return m.SequenceID
	}
	return 0
}

type Msg struct {
	Operation string `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	// Types that are valid to be assigned to Arg:
	//	*Msg_Ppm
	//	*Msg_Pm
	//	*Msg_Cm
	//	*Msg_Vcm
	//	*Msg_Crm
	Arg                  isMsg_Arg `protobuf_oneof:"arg"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Msg) Reset()         { *m = Msg{} }
func (m *Msg) String() string { return proto.CompactTextString(m) }
func (*Msg) ProtoMessage()    {}
func (*Msg) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{17}
}

func (m *Msg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Msg.Unmarshal(m, b)
}
func (m *Msg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Msg.Marshal(b, m, deterministic)
}
func (m *Msg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Msg.Merge(m, src)
}
func (m *Msg) XXX_Size() int {
	return xxx_messageInfo_Msg.Size(m)
}
func (m *Msg) XXX_DiscardUnknown() {
	xxx_messageInfo_Msg.DiscardUnknown(m)
}

var xxx_messageInfo_Msg proto.InternalMessageInfo

func (m *Msg) GetOperation() string {
	if m != nil {
		return m.Operation
	}
	return ""
}

type isMsg_Arg interface {
	isMsg_Arg()
}

type Msg_Ppm struct {
	Ppm *PrePrepareMsg `protobuf:"bytes,2,opt,name=ppm,proto3,oneof"`
}

type Msg_Pm struct {
	Pm *PrepareMsg `protobuf:"bytes,3,opt,name=pm,proto3,oneof"`
}

type Msg_Cm struct {
	Cm *CommitMsg `protobuf:"bytes,4,opt,name=cm,proto3,oneof"`
}

type Msg_Vcm struct {
	Vcm *ViewChangeMsg `protobuf:"bytes,5,opt,name=vcm,proto3,oneof"`
}

type Msg_Crm struct {
	Crm *ClientResponse `protobuf:"bytes,6,opt,name=crm,proto3,oneof"`
}

func (*Msg_Ppm) isMsg_Arg() {}

func (*Msg_Pm) isMsg_Arg() {}

func (*Msg_Cm) isMsg_Arg() {}

func (*Msg_Vcm) isMsg_Arg() {}

func (*Msg_Crm) isMsg_Arg() {}

func (m *Msg) GetArg() isMsg_Arg {
	if m != nil {
		return m.Arg
	}
	return nil
}

func (m *Msg) GetPpm() *PrePrepareMsg {
	if x, ok := m.GetArg().(*Msg_Ppm); ok {
		return x.Ppm
	}
	return nil
}

func (m *Msg) GetPm() *PrepareMsg {
	if x, ok := m.GetArg().(*Msg_Pm); ok {
		return x.Pm
	}
	return nil
}

func (m *Msg) GetCm() *CommitMsg {
	if x, ok := m.GetArg().(*Msg_Cm); ok {
		return x.Cm
	}
	return nil
}

func (m *Msg) GetVcm() *ViewChangeMsg {
	if x, ok := m.GetArg().(*Msg_Vcm); ok {
		return x.Vcm
	}
	return nil
}

func (m *Msg) GetCrm() *ClientResponse {
	if x, ok := m.GetArg().(*Msg_Crm); ok {
		return x.Crm
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Msg) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Msg_Ppm)(nil),
		(*Msg_Pm)(nil),
		(*Msg_Cm)(nil),
		(*Msg_Vcm)(nil),
		(*Msg_Crm)(nil),
	}
}

func init() {
	proto.RegisterEnum("pb.Op", Op_name, Op_value)
	proto.RegisterType((*Key)(nil), "pb.Key")
	proto.RegisterType((*Value)(nil), "pb.Value")
	proto.RegisterType((*KeyValue)(nil), "pb.KeyValue")
	proto.RegisterType((*Success)(nil), "pb.Success")
	proto.RegisterType((*Error)(nil), "pb.Error")
	proto.RegisterType((*CASArg)(nil), "pb.CASArg")
	proto.RegisterType((*Empty)(nil), "pb.Empty")
	proto.RegisterType((*Redirect)(nil), "pb.Redirect")
	proto.RegisterType((*Result)(nil), "pb.Result")
	proto.RegisterType((*Command)(nil), "pb.Command")
	proto.RegisterType((*Entry)(nil), "pb.Entry")
	proto.RegisterType((*ClientRequest)(nil), "pb.ClientRequest")
	proto.RegisterType((*PrePrepareMsg)(nil), "pb.PrePrepareMsg")
	proto.RegisterType((*PrepareMsg)(nil), "pb.PrepareMsg")
	proto.RegisterType((*CommitMsg)(nil), "pb.CommitMsg")
	proto.RegisterType((*ViewChangeMsg)(nil), "pb.ViewChangeMsg")
	proto.RegisterType((*ClientResponse)(nil), "pb.ClientResponse")
	proto.RegisterType((*Msg)(nil), "pb.Msg")
}

func init() { proto.RegisterFile("kv.proto", fileDescriptor_2216fe83c9c12408) }

var fileDescriptor_2216fe83c9c12408 = []byte{
	// 799 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x55, 0x5d, 0x6e, 0xdb, 0x46,
	0x10, 0x16, 0xb9, 0xa2, 0x24, 0x8e, 0x6a, 0x43, 0x1d, 0x14, 0xad, 0x9a, 0x38, 0x8e, 0x4b, 0x34,
	0x41, 0xe0, 0xa2, 0x7e, 0x50, 0x4e, 0xe0, 0x28, 0x42, 0x64, 0xb8, 0x41, 0x8c, 0x55, 0x90, 0x77,
	0x9a, 0x9a, 0x32, 0x84, 0xb5, 0xe4, 0x76, 0x77, 0x4d, 0x57, 0xe8, 0x65, 0x7a, 0x8c, 0x3e, 0xf7,
	0x2a, 0xbd, 0x48, 0xb1, 0xcb, 0x65, 0xc4, 0xc8, 0xee, 0x4b, 0x81, 0xf6, 0x49, 0xf3, 0xf3, 0x0d,
	0xbf, 0x99, 0xd9, 0x99, 0x11, 0x8c, 0x6e, 0xea, 0x33, 0xa9, 0x2a, 0x53, 0x61, 0x28, 0xaf, 0x93,
	0x6f, 0x80, 0x5d, 0xd2, 0x16, 0x27, 0xc0, 0x6e, 0x68, 0x3b, 0x0d, 0x4e, 0x82, 0x17, 0x31, 0xb7,
	0x62, 0xf2, 0x04, 0xa2, 0x0f, 0xe9, 0xe6, 0x96, 0xf0, 0x2b, 0x88, 0x6a, 0x2b, 0x78, 0x67, 0xa3,
	0x24, 0x33, 0x18, 0x5d, 0xd2, 0xb6, 0x41, 0xdc, 0x0b, 0xde, 0xc5, 0x84, 0xdd, 0x98, 0x18, 0x86,
	0xab, 0xdb, 0x2c, 0x23, 0xad, 0x93, 0x6f, 0x21, 0x5a, 0x28, 0x55, 0x29, 0x1b, 0x2b, 0x74, 0xde,
	0xc6, 0x0a, 0x9d, 0x27, 0x6f, 0x60, 0x30, 0x3f, 0x5f, 0x9d, 0xab, 0x1c, 0x8f, 0x20, 0xbc, 0xa9,
	0x9d, 0x6b, 0x3c, 0xfb, 0xe2, 0x4c, 0x5e, 0x9f, 0xb5, 0x8c, 0x3c, 0xbc, 0xa9, 0xf1, 0x69, 0x97,
	0x63, 0x3c, 0x8b, 0x2d, 0xa0, 0xf1, 0x7a, 0xba, 0x21, 0x44, 0x0b, 0x21, 0xcd, 0x36, 0x49, 0x60,
	0xc4, 0x69, 0x5d, 0x28, 0xca, 0x0c, 0x7e, 0x0d, 0x03, 0x4d, 0xaa, 0x26, 0xe5, 0x29, 0xbd, 0x96,
	0xfc, 0x06, 0x03, 0x4e, 0xfa, 0x76, 0x63, 0xf0, 0x14, 0x46, 0xca, 0xa3, 0xbb, 0xdc, 0xed, 0x17,
	0x96, 0x3d, 0xfe, 0xc9, 0x8f, 0xc7, 0x2e, 0xc3, 0xf0, 0x7e, 0x86, 0xcb, 0x9e, 0xcb, 0xf1, 0x31,
	0x04, 0x7a, 0xca, 0x9c, 0x7b, 0x6c, 0xdd, 0xbe, 0xfc, 0x65, 0x8f, 0x07, 0xfa, 0xd5, 0x08, 0x06,
	0xca, 0x51, 0x26, 0x7f, 0x04, 0x30, 0x9c, 0x57, 0x42, 0xa4, 0xe5, 0x1a, 0xbf, 0x87, 0xb8, 0x92,
	0xa4, 0x52, 0x53, 0x54, 0xa5, 0xe3, 0x3f, 0x9c, 0x0d, 0x6c, 0xe8, 0x3b, 0xc9, 0x77, 0x0e, 0x7c,
	0x0c, 0x2c, 0x27, 0xe3, 0x99, 0x87, 0x9e, 0x79, 0xd9, 0xe3, 0xd6, 0x8a, 0x27, 0xc0, 0x34, 0x19,
	0xcf, 0xbb, 0x9f, 0x96, 0x75, 0xe1, 0x77, 0x10, 0x65, 0x1b, 0x4a, 0xd5, 0xb4, 0xbf, 0xeb, 0x9d,
	0xeb, 0xd5, 0xb2, 0xc7, 0x1b, 0x0f, 0x1e, 0x03, 0xcb, 0x52, 0x3d, 0x8d, 0x1c, 0x00, 0x2c, 0xa0,
	0x79, 0x15, 0xfb, 0x89, 0x2c, 0xd5, 0xaf, 0x22, 0x60, 0xa9, 0xca, 0x93, 0x2b, 0x88, 0x16, 0xa5,
	0x51, 0x5b, 0x44, 0xe8, 0x1b, 0x52, 0xc2, 0xa5, 0xcc, 0xb8, 0x93, 0xed, 0x18, 0x14, 0xe5, 0x9a,
	0x7e, 0x75, 0x79, 0x32, 0xde, 0x28, 0xf8, 0x04, 0x58, 0x26, 0xd6, 0xdd, 0xb6, 0xf8, 0xda, 0xb9,
	0xb5, 0x27, 0x1f, 0xe1, 0x60, 0xbe, 0x29, 0xa8, 0x34, 0x9c, 0x7e, 0xb9, 0x25, 0x6d, 0x5a, 0x7c,
	0xf0, 0x30, 0x1e, 0x8f, 0x20, 0x36, 0x85, 0x20, 0x6d, 0x52, 0x21, 0x3d, 0xd1, 0xce, 0x80, 0x8f,
	0x60, 0x94, 0xb9, 0xaf, 0x5d, 0xbc, 0x76, 0x8c, 0x31, 0xff, 0xa4, 0x27, 0xbf, 0x07, 0x70, 0x70,
	0xa5, 0xe8, 0x4a, 0x91, 0x4c, 0x15, 0xbd, 0xd5, 0xb9, 0x9d, 0x8e, 0xba, 0xa0, 0xbb, 0x8b, 0xb5,
	0x2f, 0xc3, 0x6b, 0x78, 0x0c, 0xa0, 0x6d, 0x36, 0x65, 0x46, 0x17, 0xaf, 0x3d, 0x49, 0xc7, 0x62,
	0xe3, 0xd6, 0x45, 0x4e, 0xda, 0x78, 0x0e, 0xaf, 0xe1, 0x0f, 0x30, 0x54, 0x4d, 0x15, 0xbe, 0xd3,
	0x5f, 0xba, 0xf4, 0xbb, 0xe5, 0xf1, 0x16, 0x61, 0x3b, 0x58, 0x56, 0x6b, 0x72, 0x2d, 0x8f, 0xb9,
	0x93, 0x13, 0x09, 0xf0, 0x1f, 0xa6, 0xd7, 0x32, 0xf6, 0x3b, 0x8c, 0x15, 0xc4, 0xb6, 0xbd, 0x85,
	0xf9, 0xbf, 0x08, 0xb7, 0x70, 0xf0, 0xa1, 0xa0, 0xbb, 0xf9, 0xc7, 0xb4, 0xcc, 0x5d, 0x95, 0x76,
	0x92, 0xb6, 0xb2, 0xbd, 0x37, 0x4e, 0xc6, 0x29, 0x0c, 0x4b, 0xba, 0xb3, 0x38, 0xcf, 0xd6, 0xaa,
	0xf8, 0x1c, 0x0e, 0x37, 0xa9, 0x36, 0xab, 0x5d, 0x3a, 0xcc, 0x01, 0xf6, 0xac, 0x0f, 0x76, 0xf7,
	0xcf, 0x00, 0x0e, 0xdb, 0xc7, 0xd0, 0xb2, 0x2a, 0x35, 0xfd, 0x63, 0xc5, 0xff, 0x7a, 0xca, 0x1e,
	0xaa, 0x19, 0x4f, 0x01, 0xec, 0x6f, 0x73, 0x71, 0xba, 0x3b, 0xd6, 0x58, 0x78, 0xc7, 0xbb, 0xd7,
	0xeb, 0xc1, 0x7e, 0xaf, 0x93, 0xbf, 0x02, 0x60, 0xb6, 0x6d, 0x47, 0xfb, 0x87, 0x23, 0xee, 0x1e,
	0x8c, 0x67, 0xc0, 0xa4, 0x14, 0xfe, 0x60, 0xb8, 0x29, 0xfc, 0x6c, 0xf2, 0xed, 0x56, 0x4b, 0x29,
	0xf0, 0x04, 0x42, 0x29, 0xfc, 0x6a, 0x1e, 0x7a, 0xd4, 0x0e, 0x12, 0x4a, 0x81, 0x4f, 0x21, 0xcc,
	0x84, 0x9f, 0xe6, 0x83, 0x76, 0x19, 0xdd, 0xb4, 0x58, 0x40, 0x26, 0x2c, 0x53, 0x9d, 0x09, 0x5f,
	0x94, 0x63, 0xfa, 0xec, 0x79, 0x2d, 0x53, 0x9d, 0x09, 0x7c, 0x0e, 0x2c, 0x53, 0xc2, 0xd5, 0x33,
	0x9e, 0x61, 0x77, 0x2d, 0x9a, 0x97, 0x70, 0x77, 0x46, 0x09, 0x7f, 0x67, 0x4e, 0x4f, 0x21, 0x7c,
	0x27, 0x71, 0x08, 0xec, 0xcd, 0xe2, 0xfd, 0xa4, 0x67, 0x85, 0xd5, 0xe2, 0xfd, 0x24, 0xc0, 0x18,
	0xa2, 0xf9, 0x4f, 0x8b, 0x73, 0x3e, 0x09, 0xad, 0x6d, 0x7e, 0xbe, 0x9a, 0xb0, 0xd9, 0x4b, 0x18,
	0x5e, 0xd6, 0x2b, 0x53, 0x29, 0xc2, 0x17, 0xd0, 0x9f, 0xa7, 0x9b, 0x0d, 0xde, 0xdf, 0xbb, 0x47,
	0xdd, 0x83, 0x9c, 0xf4, 0x66, 0x3f, 0x42, 0xff, 0xea, 0xfa, 0x67, 0x83, 0xcf, 0x60, 0xbc, 0xa2,
	0x72, 0x6d, 0x65, 0xdb, 0x55, 0x77, 0x5b, 0xdf, 0xea, 0x7c, 0x0f, 0x7e, 0x3d, 0x70, 0x7f, 0xa1,
	0x2f, 0xff, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x76, 0xaf, 0x1e, 0x31, 0x4e, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// KvStoreClient is the client API for KvStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type KvStoreClient interface {
	// Get the value associated with a key.
	Call(ctx context.Context, in *ClientRequest, opts ...grpc.CallOption) (*Success, error)
}

type kvStoreClient struct {
	cc *grpc.ClientConn
}

func NewKvStoreClient(cc *grpc.ClientConn) KvStoreClient {
	return &kvStoreClient{cc}
}

func (c *kvStoreClient) Call(ctx context.Context, in *ClientRequest, opts ...grpc.CallOption) (*Success, error) {
	out := new(Success)
	err := c.cc.Invoke(ctx, "/pb.KvStore/Call", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KvStoreServer is the server API for KvStore service.
type KvStoreServer interface {
	// Get the value associated with a key.
	Call(context.Context, *ClientRequest) (*Success, error)
}

func RegisterKvStoreServer(s *grpc.Server, srv KvStoreServer) {
	s.RegisterService(&_KvStore_serviceDesc, srv)
}

func _KvStore_Call_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KvStoreServer).Call(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.KvStore/Call",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KvStoreServer).Call(ctx, req.(*ClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _KvStore_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.KvStore",
	HandlerType: (*KvStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Call",
			Handler:    _KvStore_Call_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kv.proto",
}

// PbftClient is the client API for Pbft service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PbftClient interface {
	SendPbftMsg(ctx context.Context, in *Msg, opts ...grpc.CallOption) (*Success, error)
}

type pbftClient struct {
	cc *grpc.ClientConn
}

func NewPbftClient(cc *grpc.ClientConn) PbftClient {
	return &pbftClient{cc}
}

func (c *pbftClient) SendPbftMsg(ctx context.Context, in *Msg, opts ...grpc.CallOption) (*Success, error) {
	out := new(Success)
	err := c.cc.Invoke(ctx, "/pb.Pbft/SendPbftMsg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PbftServer is the server API for Pbft service.
type PbftServer interface {
	SendPbftMsg(context.Context, *Msg) (*Success, error)
}

func RegisterPbftServer(s *grpc.Server, srv PbftServer) {
	s.RegisterService(&_Pbft_serviceDesc, srv)
}

func _Pbft_SendPbftMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Msg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PbftServer).SendPbftMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Pbft/SendPbftMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PbftServer).SendPbftMsg(ctx, req.(*Msg))
	}
	return interceptor(ctx, in, info, handler)
}

var _Pbft_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Pbft",
	HandlerType: (*PbftServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendPbftMsg",
			Handler:    _Pbft_SendPbftMsg_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kv.proto",
}
